language: python
dist: xenial
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
matrix:
  fast_finish: true

install:
 # The default pip doesn't properly support pre-release version specifiers.
 - pip install -U pip
 - pip install tox tox-travis
branches:
 only:
  - master
  - develop
  - /^feature\/.+/
  - /^release\/.+/
  - /^hotfix\/.+/
  - /^v[\d\.]+/
script: tox -r
after_success:
  - pip install --quiet python-coveralls
  - coveralls
